#!/bin/bash

## Copyright (C) 2019 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

## sudo runs this helper as the invoking user with the environment inherited
## unchanged, but a .desktop launcher on a minimal Wayland compositor may not
## export the variables yad needs to reach the display. Rederive them here.
# shellcheck source=../../../../helper-scripts/usr/libexec/helper-scripts/askpass_gui_env.bsh
source "${HELPER_SCRIPTS_PATH:-}"/usr/libexec/helper-scripts/askpass_gui_env.bsh
askpass_gui_env

title="$0: password required for $(whoami) to perform action as superuser"

yad --password --title="$title"
